# Generated by Django 5.2.5 on 2025-08-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_patient_dob_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='pname',
        ),
    ]
